development: &default
  adapter: postgresql
  encoding: unicode
  database: call_cp_development
  pool: 5
  username: postgres
  password: 1111
  host: 127.0.0.1

test:
  <<: *default
  database: call_cp_test